/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyLinkableValue": {
      "foo": string
      "type": "sst.sst.Linkable"
    }
    "MyNodeApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MyPythonApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MyPythonContainerApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}