# Automatically generated by SST
# pylint: disable=all
# ruff: noqa
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class PackageHandler:
        name: str
        type: str
        url: str
    class RootHandler:
        name: str
        type: str
        url: str
    class WorkspaceHandler:
        name: str
        type: str
        url: str

