# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class MyBucket:
        name: str
        type: str
    class MyLinkableValue:
        foo: str
        type: str
    class MyPythonApi:
        name: str
        type: str
        url: str
    class MyPythonContainerApi:
        name: str
        type: str
        url: str

