package typescript

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sst/sst/v3/internal/fs"
	"github.com/sst/sst/v3/pkg/js"
	"github.com/sst/sst/v3/pkg/project/common"
)

var mapping = map[string]string{
	"aiBindings":              "Ai",
	"r2BucketBindings":        "R2Bucket",
	"d1DatabaseBindings":      "D1Database",
	"kvNamespaceBindings":     "KVNamespace",
	"queueBindings":           "Queue",
	"serviceBindings":         "Service",
	"hyperdriveBindings":      "Hyperdrive",
	"versionMetadataBindings": "WorkerVersionMetadata",
}

var header = strings.Join([]string{
	"/* This file is auto-generated by SST. Do not edit. */",
	"/* tslint:disable */",
	"/* eslint-disable */",
	"/* deno-fmt-ignore-file */",
	"/* biome-ignore-all lint: auto-generated */",
	"",
	"",
}, "\n")

var footer = strings.Join([]string{
	"",
	"import \"sst\"",
	"export {}",
}, "\n")

func Generate(root string, links common.Links) error {
	cloudflareBindings := map[string]string{}
	for name, link := range links {
		for _, include := range link.Include {
			if include.Type == "cloudflare.binding" {
				binding := include.Other["binding"].(string)
				cloudflareBindings[name] = mapping[binding]
				break
			}
		}
	}

	properties := map[string]interface{}{}
	nonCloudflareProperties := map[string]interface{}{}
	for name, link := range links {
		properties[name] = link.Properties
		if cloudflareBindings[name] == "" {
			nonCloudflareProperties[name] = link.Properties
		}
	}

	packageJsons := fs.FindDown(root, "package.json")
	rootEnv := filepath.Join(root, "sst-env.d.ts")
	for _, packageJson := range packageJsons {
		packageJsonData, err := os.ReadFile(packageJson)
		if err != nil {
			continue
		}
		var data js.PackageJson
		err = json.Unmarshal(packageJsonData, &data)
		if err != nil {
			continue
		}

		envPath := filepath.Join(filepath.Dir(packageJson), "sst-env.d.ts")

		content := ""
		if hasCloudflareTypes(data) {
			content = renderCloudflareFile(nonCloudflareProperties, cloudflareBindings)
		} else if rootEnv == envPath {
			content = renderRootFile(properties)
		} else {
			rel, err := filepath.Rel(filepath.Dir(envPath), rootEnv)
			if err != nil {
				continue
			}
			content = renderReferenceFile(filepath.ToSlash(rel))
		}

		if err := writeIfChanged(envPath, []byte(content)); err != nil {
			continue
		}
	}

	return nil
}

func hasCloudflareTypes(pkg js.PackageJson) bool {
	return pkg.Dependencies["@cloudflare/workers-types"] != "" || pkg.DevDependencies["@cloudflare/workers-types"] != ""
}

func renderRootFile(properties map[string]interface{}) string {
	var builder strings.Builder
	builder.WriteString(header)
	builder.WriteString("declare module \"sst\" {\n")
	builder.WriteString("  export interface Resource ")
	builder.WriteString(infer(properties, "  "))
	builder.WriteString("\n")
	builder.WriteString("}\n")
	builder.WriteString(footer)
	return builder.String()
}

func renderReferenceFile(rel string) string {
	var builder strings.Builder
	builder.WriteString(header)
	builder.WriteString("/// <reference path=\"")
	builder.WriteString(rel)
	builder.WriteString("\" />\n")
	builder.WriteString(footer)
	return builder.String()
}

func renderCloudflareFile(properties map[string]interface{}, cloudflareBindings map[string]string) string {
	var builder strings.Builder
	builder.WriteString(header)
	builder.WriteString("declare module \"sst\" {\n")
	builder.WriteString("  export interface Resource ")
	builder.WriteString(infer(properties, "  "))
	builder.WriteString("\n")
	builder.WriteString("}\n")

	bindings := map[string]interface{}{}
	for name, link := range cloudflareBindings {
		bindings[name] = literal{value: `import("@cloudflare/workers-types").` + link}
	}
	if len(bindings) > 0 {
		builder.WriteString("declare module \"sst\" {\n")
		builder.WriteString("  export interface Resource ")
		builder.WriteString(infer(bindings, "  "))
		builder.WriteString("\n")
		builder.WriteString("}\n")
	}

	builder.WriteString(footer)
	return builder.String()
}

func writeIfChanged(path string, next []byte) error {
	current, err := os.ReadFile(path)
	if err == nil && bytes.Equal(current, next) {
		return nil
	}
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	return os.WriteFile(path, next, 0644)
}

type literal struct {
	value string
}

func infer(input map[string]interface{}, indentArgs ...string) string {
	indent := ""
	if len(indentArgs) > 0 {
		indent = indentArgs[0]
	}
	var builder strings.Builder
	builder.WriteString("{")
	builder.WriteString("\n")
	keys := make([]string, 0, len(input))
	for key := range input {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		value := input[key]
		builder.WriteString(indent + "  \"" + key + "\": ")
		if key == "type" && len(indentArgs) == 1 {
			builder.WriteString("\"")
			builder.WriteString(value.(string))
			builder.WriteString("\"")
		} else {
			switch v := value.(type) {
			case literal:
				builder.WriteString(v.value)
			case string:
				builder.WriteString("string")
			case int:
				builder.WriteString("number")
			case float64:
				builder.WriteString("number")
			case float32:
				builder.WriteString("number")
			case bool:
				builder.WriteString("boolean")
			case map[string]interface{}:
				builder.WriteString(infer(value.(map[string]interface{}), indent+"  "))
			default:
				builder.WriteString("any")
			}
		}
		builder.WriteString("\n")
	}
	builder.WriteString(indent + "}")
	return builder.String()
}
