/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Astro": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "Database": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "StaticSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
declare module "sst" {
  export interface Resource {
    "CfBucket": import("@cloudflare/workers-types").R2Bucket
    "MyWorker": import("@cloudflare/workers-types").Service
  }
}

import "sst"
export {}