# Automatically generated by SST
# pylint: disable=all
# ruff: noqa
from typing import Any

class Resource:
    class ApiService:
        name: str
        type: str
        url: str
    class App:
        name: str
        stage: str
    class WorkerService:
        name: str
        type: str

